### PR TITLE
Closes #32 

### LINKED ISSUE #32: App crashes when opening the ToiletMapFragment
I think the problem is when `onCreateView()` is called, the `m7am` Toilet object is already gone.

### PR DESCRIPTION
**Pull request by luisramalho**
Fixes #32 - app should not crash any longer

### CODE REVIEW

File: vor-android/mobile/src/main/java/com/futurice/hereandnow/pojo/Toilet.kt [hunk 1]
```diff
@@ -1,19 +0,0 @@
-package com.futurice.hereandnow.pojo
-
-import android.content.SharedPreferences
-
-/**
- * Created by Luís Ramalho on 28/12/15.
- * <luis.ramalho@futurice.com>
- */
-class Toilet {
```
Comment (vtainio) [inline vor-android/mobile/src/main/java/com/futurice/hereandnow/pojo/Toilet.kt:9]: We could probably remove Kotlin from gradle now that it isn't used. Or was there something else as well?

Comment (luisramalho) [inline vor-android/mobile/src/main/java/com/futurice/hereandnow/pojo/Toilet.kt:9]: I feel that we can leave it and slowly try to bring Kotlin into to the app, as I become more confident with Kotlin I plan to use more thoroughly. It would actually be one of my plus points to work on this project afterwards :pray:

Comment (vtainio) [inline vor-android/mobile/src/main/java/com/futurice/hereandnow/pojo/Toilet.kt:9]: :+1:
